services:
  openwrtstats:
    image: lov432/openwrt-stats:v2
    container_name: openwrtstats
    volumes:
      - ./drizzle/db/:/app/drizzle/db/
    ports:
      - 3000:3000
    restart: unless-stopped
