name: docker-build

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: |
            lov432/openwrt-stats:${{ github.ref_name }}
            ${{ github.ref_name == 'master' && 'lov432/openwrt-stats:latest' || '' }}
            lov432/openwrt-stats:${{ github.sha }}
