name: Build & Publish Docker Image Of Commit to Docker Hub

on:
  push:

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & Publish
      - name: Build & Publish Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lov432/openwrt-stats:${{ github.ref_name }}-${{ github.sha }}
